[package]
name = "aranya-daemon-api"
description = "UDS tarpc API between the Aranya client and the daemon"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lints]
workspace = true


[dependencies]
aranya-crypto = { workspace = true }
aranya-fast-channels = { workspace = true }
aranya-util = { workspace = true }

postcard = { workspace = true }
serde = { workspace = true }
tarpc = { workspace = true }
thiserror = { workspace = true }


[package.metadata.cargo-machete]
ignored = ["postcard"]
