[package]
name = "aranya-daemon-api"
description = "UDS tarpc API between the Aranya client and the daemon"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lints]
workspace = true


[dependencies]
aranya-crypto = { workspace = true }
aranya-fast-channels = { workspace = true }
aranya-util = { workspace = true }
buggy = { workspace = true }
spideroak-base58 = { workspace = true, features = ["std"] }

anyhow = { workspace = true }
bytes = { version = "1", features = ["serde"] }
futures-util = { workspace = true }
pin-project = { version = "1.1" }
postcard = { workspace = true }
serde = { workspace = true }
serde_bytes = { version = "0.11" }
tarpc = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.44" }
tokio-serde = { version = "0.9", features = ["messagepack"] }
tracing = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["postcard"]
