[package]
name = "aranya-daemon-api"
description = "IPC API between the Aranya client and daemon"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lints]
workspace = true


[dependencies]
aranya-crypto = { workspace = true }
aranya-util = { workspace = true }
buggy = { workspace = true }

anyhow = { workspace = true }
bytes = { version = "1", features = ["serde"] }
ciborium = { workspace = true }
futures-util = { workspace = true }
pin-project = { version = "1.1" }
postcard = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
tarpc = { workspace = true }
tokio = { workspace = true }
tokio-serde = { version = "0.9", features = ["messagepack"] }
tracing = { workspace = true }

[dev-dependencies]
backon = { workspace = true }
tempfile = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

# Used by `custom_id!`.
[package.metadata.cargo-machete]
ignored = ["postcard"]
