[package]
name = "aranya-daemon-api"
description = "API Interface between Aranya client and daemon, handling type conversion between internal and external types"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lints]
workspace = true


[dependencies]
aranya-crypto = { workspace = true }
aranya-fast-channels = { workspace = true }
aranya-util = { workspace = true }
spideroak-base58 = { workspace = true, features = ["std"] }

anyhow = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
tarpc = { workspace = true }
tracing = { workspace = true }


[package.metadata.cargo-machete]
ignored = ["postcard"]
