//! Code generated by `policy-ifgen`. DO NOT EDIT.
#![allow(clippy::duplicated_attributes)]
#![allow(clippy::enum_variant_names)]
#![allow(missing_docs)]
#![allow(non_snake_case)]
#![allow(unused_imports)]
extern crate alloc;
use alloc::{string::String, vec::Vec};
use policy_ifgen::{
    macros::{actions, effect, effects, value},
    ClientError, Id, Value,
};
/// Enum of policy effects that can occur in response to a policy action.
#[effects]
pub enum Effect {}
/// Implements all supported policy actions.
#[actions]
pub trait ActorExt {}
