unstable_features = true
style_edition = "2024"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
wrap_comments = true
# Manually override comment_width for capi crates
comment_width = 65