name: "Setup build tools"
description: "Action for setting up build tools"

inputs:
  gh-token:
    description: "github.com Access Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up git
      run: |
        git config --global --replace-all url."https://${{ inputs.gh-token }}@github.com/".insteadOf 'https://github.com/'
        echo "CARGO_NET_GIT_FETCH_WITH_CLI=true" >> $GITHUB_ENV
      shell: bash

    - name: Version info
      shell: bash
      run: |
        cargo --version --verbose
        ldd --version
        clang --version
        gcc --version
        cmake --version

    - name: Install sccache
      uses: aranya-project/sccache-action@main
      with:
        version: "v0.7.7"

    - name: Configure sccache
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
      shell: bash

    - name: Install cargo-make
      run: cargo install --version '0.37.11' --locked cargo-make
      shell: bash
