
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.actix]
url = "https://raw.githubusercontent.com/actix/supply-chain/main/audits.toml"

[imports.aranya-core]
url = "https://raw.githubusercontent.com/aranya-project/aranya-core/refs/heads/main/supply-chain/audits.toml"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.cargo-vet]
url = "https://raw.githubusercontent.com/mozilla/cargo-vet/refs/heads/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.aranya-client]
audit-as-crates-io = false

[policy.aranya-daemon]
audit-as-crates-io = false

[policy.aranya-daemon-api]
audit-as-crates-io = false

[policy.aranya-keygen]
audit-as-crates-io = false

[policy.aranya-util]
audit-as-crates-io = false

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.aead]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.aes-gcm]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.6.18"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.6"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.83"
criteria = "safe-to-deploy"

[[exemptions.atomic-polyfill]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.backon]]
version = "1.3.0"
criteria = "safe-to-run"

[[exemptions.backtrace]]
version = "0.3.74"
criteria = "safe-to-deploy"

[[exemptions.base16ct]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.bimap]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.23"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.23"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.18"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.const-default]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.const_format]]
version = "0.2.34"
criteria = "safe-to-deploy"

[[exemptions.const_format_proc_macros]]
version = "0.2.34"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.crypto-bigint]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.3"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.9"
criteria = "safe-to-deploy"

[[exemptions.deser-hjson]]
version = "2.2.4"
criteria = "safe-to-deploy"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.ecdsa]]
version = "0.16.9"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.3"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.educe]]
version = "0.5.11"
criteria = "safe-to-deploy"

[[exemptions.elliptic-curve]]
version = "0.13.8"
criteria = "safe-to-deploy"

[[exemptions.embedded-io]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.enum-ordinalize]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.enum-ordinalize-derive]]
version = "4.3.1"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.ff]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.ghash]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-deploy"

[[exemptions.gloo-timers]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.group]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.2"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.7.17"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.76"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.168"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.markdown]]
version = "1.0.0-alpha.17"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.5"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.20.2"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-semantic-conventions]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.p256]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.p384]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.10"
criteria = "safe-to-run"

[[exemptions.paste]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.pest]]
version = "2.7.15"
criteria = "safe-to-deploy"

[[exemptions.pest_derive]]
version = "2.7.15"
criteria = "safe-to-deploy"

[[exemptions.pest_generator]]
version = "2.7.15"
criteria = "safe-to-deploy"

[[exemptions.pest_meta]]
version = "2.7.15"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.polyval]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.postcard]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.postcard-derive]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.20"
criteria = "safe-to-deploy"

[[exemptions.pretty_assertions]]
version = "1.4.1"
criteria = "safe-to-run"

[[exemptions.prettyplease]]
version = "0.2.25"
criteria = "safe-to-deploy"

[[exemptions.primeorder]]
version = "0.13.6"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.8"
criteria = "safe-to-run"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.29"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.42"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.scc]]
version = "2.2.5"
criteria = "safe-to-run"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.sdd]]
version = "3.0.4"
criteria = "safe-to-run"

[[exemptions.sec1]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.133"
criteria = "safe-to-deploy"

[[exemptions.serde_yaml]]
version = "0.9.34+deprecated"
criteria = "safe-to-deploy"

[[exemptions.serial_test]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.serial_test_derive]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.siphasher]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.8"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.90"
criteria = "safe-to-deploy"

[[exemptions.tarpc]]
version = "0.35.0"
criteria = "safe-to-deploy"

[[exemptions.tarpc-plugins]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.14.0"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.6"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.6"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.42.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-serde]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.13"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.41"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.28"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.33"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-opentelemetry]]
version = "0.27.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.19"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.ucd-trie]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.unicode-id]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.unsafe-libyaml]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.vec1]]
version = "1.12.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "1.0.1"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-deploy"
