
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.actix]
url = "https://raw.githubusercontent.com/actix/supply-chain/main/audits.toml"

[imports.aranya-core]
url = "https://raw.githubusercontent.com/aranya-project/aranya-core/refs/heads/main/supply-chain/audits.toml"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.cargo-vet]
url = "https://raw.githubusercontent.com/mozilla/cargo-vet/refs/heads/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.google-rust-crate-audits]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.aranya-client]
audit-as-crates-io = false

[policy.aranya-daemon]
audit-as-crates-io = false

[policy.aranya-daemon-api]
audit-as-crates-io = false

[policy.aranya-keygen]
audit-as-crates-io = false

[policy.aranya-util]
audit-as-crates-io = false

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.atomic-polyfill]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.backon]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.bimap]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.clang-sys]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.cobs]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.condtype]]
version = "1.3.0"
criteria = "safe-to-run"

[[exemptions.const-default]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.const_format]]
version = "0.2.34"
criteria = "safe-to-deploy"

[[exemptions.const_format_proc_macros]]
version = "0.2.34"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.cuckoofilter]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.9"
criteria = "safe-to-deploy"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-run"

[[exemptions.divan]]
version = "0.1.21"
criteria = "safe-to-run"

[[exemptions.divan-macros]]
version = "0.1.21"
criteria = "safe-to-run"

[[exemptions.educe]]
version = "0.5.11"
criteria = "safe-to-deploy"

[[exemptions.embedded-io]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.endian-type]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.enum-ordinalize]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.enum-ordinalize-derive]]
version = "4.3.1"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.fs_extra]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.gloo-timers]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.hash_hasher]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.7.17"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.markdown]]
version = "1.0.0-alpha.17"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.metrics]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.metrics-exporter-dogstatsd]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.metrics-exporter-prometheus]]
version = "0.17.2"
criteria = "safe-to-deploy"

[[exemptions.metrics-exporter-tcp]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.metrics-util]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.multimap]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.nibble_vec]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.ntapi]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.objc2-core-foundation]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.objc2-io-kit]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.5"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.20.2"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-semantic-conventions]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.postcard-derive]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.20"
criteria = "safe-to-deploy"

[[exemptions.pretty_assertions]]
version = "1.4.1"
criteria = "safe-to-run"

[[exemptions.prost]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.prost-build]]
version = "0.13.5"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.prost-types]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.quanta]]
version = "0.12.6"
criteria = "safe-to-deploy"

[[exemptions.radix_trie]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.s2n-codec]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.s2n-quic-core]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.s2n-quic-crypto]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.s2n-quic-platform]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.s2n-quic-transport]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.serial_test]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.serial_test_derive]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.siphasher]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.sketches-ddsketch]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.tokio-serde]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.vec1]]
version = "1.12.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "1.0.1"
criteria = "safe-to-run"
