
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.actix]
url = "https://raw.githubusercontent.com/actix/supply-chain/main/audits.toml"

[imports.aranya-core]
url = "https://raw.githubusercontent.com/aranya-project/aranya-core/refs/heads/main/supply-chain/audits.toml"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.cargo-vet]
url = "https://raw.githubusercontent.com/mozilla/cargo-vet/refs/heads/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.google-rust-crate-audits]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.aranya-client]
audit-as-crates-io = false

[policy.aranya-daemon]
audit-as-crates-io = false

[policy.aranya-daemon-api]
audit-as-crates-io = false

[policy.aranya-keygen]
audit-as-crates-io = false

[policy.aranya-util]
audit-as-crates-io = false

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.aead]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.aes-gcm]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.age]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.83"
criteria = "safe-to-deploy"

[[exemptions.atomic-polyfill]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-rs]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-sys]]
version = "0.28.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.74"
criteria = "safe-to-deploy"

[[exemptions.base16ct]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.bimap]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.clang-sys]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.23"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.18"
criteria = "safe-to-deploy"

[[exemptions.condtype]]
version = "1.3.0"
criteria = "safe-to-run"

[[exemptions.const-default]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.const_format]]
version = "0.2.34"
criteria = "safe-to-deploy"

[[exemptions.const_format_proc_macros]]
version = "0.2.34"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.crypto-bigint]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.cuckoofilter]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.3"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.9"
criteria = "safe-to-deploy"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.divan]]
version = "0.1.21"
criteria = "safe-to-run"

[[exemptions.divan-macros]]
version = "0.1.21"
criteria = "safe-to-run"

[[exemptions.ecdsa]]
version = "0.16.9"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.3"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.educe]]
version = "0.5.11"
criteria = "safe-to-deploy"

[[exemptions.elliptic-curve]]
version = "0.13.8"
criteria = "safe-to-deploy"

[[exemptions.endian-type]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.enum-ordinalize]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.enum-ordinalize-derive]]
version = "4.3.1"
criteria = "safe-to-deploy"

[[exemptions.ff]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.fs_extra]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures-lite]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.ghash]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.gloo-timers]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.group]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.4.11"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.hash_hasher]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.2"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.7.17"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.http-body-util]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.27.7"
criteria = "safe-to-deploy"

[[exemptions.hyper-util]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.76"
criteria = "safe-to-deploy"

[[exemptions.lazycell]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.174"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.markdown]]
version = "1.0.0-alpha.17"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.metrics]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.metrics-exporter-dogstatsd]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.metrics-exporter-prometheus]]
version = "0.17.2"
criteria = "safe-to-deploy"

[[exemptions.metrics-exporter-tcp]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.metrics-util]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.multimap]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.nibble_vec]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.ntapi]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.objc2-core-foundation]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.objc2-io-kit]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.5"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.20.2"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-semantic-conventions]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "4.6.0"
criteria = "safe-to-deploy"

[[exemptions.p256]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.p384]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.parking]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.paste]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.pest]]
version = "2.7.15"
criteria = "safe-to-deploy"

[[exemptions.pest_derive]]
version = "2.7.15"
criteria = "safe-to-deploy"

[[exemptions.pest_generator]]
version = "2.7.15"
criteria = "safe-to-deploy"

[[exemptions.pest_meta]]
version = "2.7.15"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.polyval]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.postcard-derive]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.20"
criteria = "safe-to-deploy"

[[exemptions.pretty_assertions]]
version = "1.4.1"
criteria = "safe-to-run"

[[exemptions.prettyplease]]
version = "0.2.25"
criteria = "safe-to-deploy"

[[exemptions.primeorder]]
version = "0.13.6"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.prost-build]]
version = "0.13.5"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.prost-types]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.quanta]]
version = "0.12.6"
criteria = "safe-to-deploy"

[[exemptions.radix_trie]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.rand_hc]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.rand_xoshiro]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.regex-lite]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.42"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.28"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.3"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.s2n-codec]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.s2n-quic-core]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.s2n-quic-crypto]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.s2n-quic-platform]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.s2n-quic-transport]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.scc]]
version = "2.2.5"
criteria = "safe-to-run"

[[exemptions.schannel]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.sdd]]
version = "3.0.4"
criteria = "safe-to-run"

[[exemptions.sec1]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "3.2.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.14.0"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.133"
criteria = "safe-to-deploy"

[[exemptions.serde_yaml]]
version = "0.9.34+deprecated"
criteria = "safe-to-deploy"

[[exemptions.serial_test]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.serial_test_derive]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.siphasher]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.sketches-ddsketch]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.8"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.90"
criteria = "safe-to-deploy"

[[exemptions.tarpc]]
version = "0.35.0"
criteria = "safe-to-deploy"

[[exemptions.tarpc-plugins]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.6"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.6"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.42.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.2"
criteria = "safe-to-deploy"

[[exemptions.tokio-serde]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.13"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing-opentelemetry]]
version = "0.27.0"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.ucd-trie]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.unicode-id]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.unsafe-libyaml]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.vec1]]
version = "1.12.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "1.0.1"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.24"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.24"
criteria = "safe-to-deploy"
