//! Distributed tracing context utilities.
//!
//! This module provides helpers for extracting and propagating RPC trace IDs
//! from tarpc context throughout the daemon's execution.

pub use tarpc::trace::TraceId;
use tracing::Span;

/// Extracts the trace ID from a tarpc context.
///
/// The trace ID is generated by the client and included in the request.
/// If no trace ID is found in the context, a new one is generated.
///
pub fn extract_trace_id(ctx: &tarpc::context::Context) -> TraceId {
    ctx.trace_context.trace_id
}

/// Records the trace ID on the provided span.
pub fn record_trace_id(span: &Span, trace_id: TraceId) {
    span.record("trace_id", tracing::field::display(trace_id));
}

/// Records the trace ID on the current span.
pub fn record_current_span_trace_id(trace_id: TraceId) {
    record_trace_id(&Span::current(), trace_id);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_trace_id_creation() {
        let trace_id = TraceId::default();
        assert!(!trace_id.to_string().is_empty());
    }

    #[tokio::test]
    async fn test_extract_trace_id() {
        let ctx = tarpc::context::current();
        let trace_id = extract_trace_id(&ctx);
        assert!(!trace_id.to_string().is_empty());
    }
}
