name: "Build"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
    secrets:
      CC_BUILD_TOKEN:
        required: true
      GH_DOTCOM_TOKEN:
        required: true

env:
  REV: ${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.workflow }}
  cancel-in-progress: true

jobs:
  build-release:
    strategy:
      matrix:
        include:
          - runner: "ubuntu2404-arm64-4core"
            artifact: "aranya-daemon-aarch64-unknown-linux-gnu"
          - runner: "ubuntu-latest"
            artifact: "aranya-daemon-x86_64-unknown-linux-gnu"
    name: build daemon ${{ matrix.artifact }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build code
        run: |
          cargo make build-code
          cargo make tgz-daemon

      - name: Verify build didn't change any checked-in files
        run: cargo make git-unchanged

      - name: Publish daemon
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: aranya-daemon.tar.gz
          if-no-files-found: error

  build-aranya-lib:
    strategy:
      matrix:
        include:
          - runner: "ubuntu2404-arm64-4core"
            artifact: "aranya-client-capi-aarch64-unknown-linux-gnu"
          - runner: "ubuntu-latest"
            artifact: "aranya-client-capi-x86_64-unknown-linux-gnu"
    name: build lib ${{ matrix.artifact }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Aranya Shared Library
        run: |
          cargo make build-capi-lib
          cargo make build-capi-header
          cargo make tgz-capi

      - name: Publish aranya lib
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: aranya-client-lib.tar.gz
          if-no-files-found: error
