name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
      - 45-host-doxygen-docs-on-gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: aranya-project/doxygen-github-pages-action@main
        with:
          folder: ${{ github.workspace }}/crates/aranya-client-capi/docs/html
          config_file: ${{ github.workspace }}/crates/aranya-client-capi/Doxyfile
          github_token: ${{ secrets.GITHUB_TOKEN }}
