name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
      - 45-host-doxygen-docs-on-gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Generate Doxygen docs
        run: |
          cargo make build-capi-docs

      - name: Add a .nojekyll file before deploying to GitHub pages so files with underscores work
        run: |
          touch ${{ github.workspace }}/crates/aranya-client-capi/docs/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: aranya-project/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ${{ github.workspace }}/crates/aranya-client-capi/docs/html
