# Workflow for automating Rust crate release.

name: Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  # Release unreleased crates and create a git tag
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Install cargo-release
        uses: aranya-project/install-action@main
        with:
          tool: cargo-release@0.25.15

      - name: Publish to crates.io
        run: |
          cargo release publish -v --execute
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.ARANYA_BOT_CRATESIO_CARGO_LOGIN_KEY }}

      - name: Push tag to github
        run: |
          cargo release tag -v --execute
          cargo release push -v --execute
        env:
          # TODO: Use PAT so it will trigger publish.yml
          # <https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow>
          GITHUB_TOKEN: ${{ github.token }}
